/**
 * @file Automatically generated by barrelsby.
 */

import * as authv1beta1authts from "./auth/v1beta1/auth"
import * as authv1beta1genesists from "./auth/v1beta1/genesis"
import * as authv1beta1queryts from "./auth/v1beta1/query"
import * as authv1beta1querylcdts from "./auth/v1beta1/query.lcd"
import * as authv1beta1queryrpcQueryts from "./auth/v1beta1/query.rpc.Query"
import * as authv1beta1txts from "./auth/v1beta1/tx"
import * as authv1beta1txaminots from "./auth/v1beta1/tx.amino"
import * as authv1beta1txregistryts from "./auth/v1beta1/tx.registry"
import * as authv1beta1txrpcmsgts from "./auth/v1beta1/tx.rpc.msg"
import * as authzv1beta1authzts from "./authz/v1beta1/authz"
import * as authzv1beta1eventts from "./authz/v1beta1/event"
import * as authzv1beta1genesists from "./authz/v1beta1/genesis"
import * as authzv1beta1queryts from "./authz/v1beta1/query"
import * as authzv1beta1querylcdts from "./authz/v1beta1/query.lcd"
import * as authzv1beta1queryrpcQueryts from "./authz/v1beta1/query.rpc.Query"
import * as authzv1beta1txts from "./authz/v1beta1/tx"
import * as authzv1beta1txaminots from "./authz/v1beta1/tx.amino"
import * as authzv1beta1txregistryts from "./authz/v1beta1/tx.registry"
import * as authzv1beta1txrpcmsgts from "./authz/v1beta1/tx.rpc.msg"
import * as bankv1beta1authzts from "./bank/v1beta1/authz"
import * as bankv1beta1bankts from "./bank/v1beta1/bank"
import * as bankv1beta1genesists from "./bank/v1beta1/genesis"
import * as bankv1beta1queryts from "./bank/v1beta1/query"
import * as bankv1beta1querylcdts from "./bank/v1beta1/query.lcd"
import * as bankv1beta1queryrpcQueryts from "./bank/v1beta1/query.rpc.Query"
import * as bankv1beta1txts from "./bank/v1beta1/tx"
import * as bankv1beta1txaminots from "./bank/v1beta1/tx.amino"
import * as bankv1beta1txregistryts from "./bank/v1beta1/tx.registry"
import * as bankv1beta1txrpcmsgts from "./bank/v1beta1/tx.rpc.msg"
import * as baseabciv1beta1abcits from "./base/abci/v1beta1/abci"
import * as basenodev1beta1queryts from "./base/node/v1beta1/query"
import * as basenodev1beta1querylcdts from "./base/node/v1beta1/query.lcd"
import * as basenodev1beta1queryrpcServicets from "./base/node/v1beta1/query.rpc.Service"
import * as basequeryv1beta1paginationts from "./base/query/v1beta1/pagination"
import * as basev1beta1coints from "./base/v1beta1/coin"
import * as consensusv1queryts from "./consensus/v1/query"
import * as consensusv1querylcdts from "./consensus/v1/query.lcd"
import * as consensusv1queryrpcQueryts from "./consensus/v1/query.rpc.Query"
import * as consensusv1txts from "./consensus/v1/tx"
import * as consensusv1txaminots from "./consensus/v1/tx.amino"
import * as consensusv1txregistryts from "./consensus/v1/tx.registry"
import * as consensusv1txrpcmsgts from "./consensus/v1/tx.rpc.msg"
import * as cryptoed25519keysts from "./crypto/ed25519/keys"
import * as cryptohdv1hdts from "./crypto/hd/v1/hd"
import * as cryptokeyringv1recordts from "./crypto/keyring/v1/record"
import * as cryptomultisigkeysts from "./crypto/multisig/keys"
import * as cryptomultisigv1beta1multisigts from "./crypto/multisig/v1beta1/multisig"
import * as cryptosecp256k1keysts from "./crypto/secp256k1/keys"
import * as cryptosecp256r1keysts from "./crypto/secp256r1/keys"
import * as distributionv1beta1distributionts from "./distribution/v1beta1/distribution"
import * as distributionv1beta1genesists from "./distribution/v1beta1/genesis"
import * as distributionv1beta1queryts from "./distribution/v1beta1/query"
import * as distributionv1beta1querylcdts from "./distribution/v1beta1/query.lcd"
import * as distributionv1beta1queryrpcQueryts from "./distribution/v1beta1/query.rpc.Query"
import * as distributionv1beta1txts from "./distribution/v1beta1/tx"
import * as distributionv1beta1txaminots from "./distribution/v1beta1/tx.amino"
import * as distributionv1beta1txregistryts from "./distribution/v1beta1/tx.registry"
import * as distributionv1beta1txrpcmsgts from "./distribution/v1beta1/tx.rpc.msg"
import * as govv1genesists from "./gov/v1/genesis"
import * as govv1govts from "./gov/v1/gov"
import * as govv1queryts from "./gov/v1/query"
import * as govv1querylcdts from "./gov/v1/query.lcd"
import * as govv1queryrpcQueryts from "./gov/v1/query.rpc.Query"
import * as govv1txts from "./gov/v1/tx"
import * as govv1txaminots from "./gov/v1/tx.amino"
import * as govv1txregistryts from "./gov/v1/tx.registry"
import * as govv1txrpcmsgts from "./gov/v1/tx.rpc.msg"
import * as govv1beta1genesists from "./gov/v1beta1/genesis"
import * as govv1beta1govts from "./gov/v1beta1/gov"
import * as govv1beta1queryts from "./gov/v1beta1/query"
import * as govv1beta1querylcdts from "./gov/v1beta1/query.lcd"
import * as govv1beta1queryrpcQueryts from "./gov/v1beta1/query.rpc.Query"
import * as govv1beta1txts from "./gov/v1beta1/tx"
import * as govv1beta1txaminots from "./gov/v1beta1/tx.amino"
import * as govv1beta1txregistryts from "./gov/v1beta1/tx.registry"
import * as govv1beta1txrpcmsgts from "./gov/v1beta1/tx.rpc.msg"
import * as ics23v1proofsts from "./ics23/v1/proofs"
import * as nftv1beta1eventts from "./nft/v1beta1/event"
import * as nftv1beta1genesists from "./nft/v1beta1/genesis"
import * as nftv1beta1nftts from "./nft/v1beta1/nft"
import * as nftv1beta1queryts from "./nft/v1beta1/query"
import * as nftv1beta1querylcdts from "./nft/v1beta1/query.lcd"
import * as nftv1beta1queryrpcQueryts from "./nft/v1beta1/query.rpc.Query"
import * as nftv1beta1txts from "./nft/v1beta1/tx"
import * as nftv1beta1txaminots from "./nft/v1beta1/tx.amino"
import * as nftv1beta1txregistryts from "./nft/v1beta1/tx.registry"
import * as nftv1beta1txrpcmsgts from "./nft/v1beta1/tx.rpc.msg"
import * as stakingv1beta1authzts from "./staking/v1beta1/authz"
import * as stakingv1beta1genesists from "./staking/v1beta1/genesis"
import * as stakingv1beta1queryts from "./staking/v1beta1/query"
import * as stakingv1beta1querylcdts from "./staking/v1beta1/query.lcd"
import * as stakingv1beta1queryrpcQueryts from "./staking/v1beta1/query.rpc.Query"
import * as stakingv1beta1stakingts from "./staking/v1beta1/staking"
import * as stakingv1beta1txts from "./staking/v1beta1/tx"
import * as stakingv1beta1txaminots from "./staking/v1beta1/tx.amino"
import * as stakingv1beta1txregistryts from "./staking/v1beta1/tx.registry"
import * as stakingv1beta1txrpcmsgts from "./staking/v1beta1/tx.rpc.msg"
import * as txsigningv1beta1signingts from "./tx/signing/v1beta1/signing"
import * as txv1beta1servicets from "./tx/v1beta1/service"
import * as txv1beta1servicelcdts from "./tx/v1beta1/service.lcd"
import * as txv1beta1servicerpcServicets from "./tx/v1beta1/service.rpc.Service"
import * as txv1beta1txts from "./tx/v1beta1/tx"
import * as upgradev1beta1queryts from "./upgrade/v1beta1/query"
import * as upgradev1beta1querylcdts from "./upgrade/v1beta1/query.lcd"
import * as upgradev1beta1queryrpcQueryts from "./upgrade/v1beta1/query.rpc.Query"
import * as upgradev1beta1txts from "./upgrade/v1beta1/tx"
import * as upgradev1beta1txaminots from "./upgrade/v1beta1/tx.amino"
import * as upgradev1beta1txregistryts from "./upgrade/v1beta1/tx.registry"
import * as upgradev1beta1txrpcmsgts from "./upgrade/v1beta1/tx.rpc.msg"
import * as upgradev1beta1upgradets from "./upgrade/v1beta1/upgrade"
export const auth = {
	v1beta1: {
		auth: authv1beta1authts,
		genesis: authv1beta1genesists,
		query: authv1beta1queryts,
		"query.lcd": authv1beta1querylcdts,
		"query.rpc.Query": authv1beta1queryrpcQueryts,
		tx: authv1beta1txts,
		"tx.amino": authv1beta1txaminots,
		"tx.registry": authv1beta1txregistryts,
		"tx.rpc.msg": authv1beta1txrpcmsgts
	}
}
export const authz = {
	v1beta1: {
		authz: authzv1beta1authzts,
		event: authzv1beta1eventts,
		genesis: authzv1beta1genesists,
		query: authzv1beta1queryts,
		"query.lcd": authzv1beta1querylcdts,
		"query.rpc.Query": authzv1beta1queryrpcQueryts,
		tx: authzv1beta1txts,
		"tx.amino": authzv1beta1txaminots,
		"tx.registry": authzv1beta1txregistryts,
		"tx.rpc.msg": authzv1beta1txrpcmsgts
	}
}
export const bank = {
	v1beta1: {
		authz: bankv1beta1authzts,
		bank: bankv1beta1bankts,
		genesis: bankv1beta1genesists,
		query: bankv1beta1queryts,
		"query.lcd": bankv1beta1querylcdts,
		"query.rpc.Query": bankv1beta1queryrpcQueryts,
		tx: bankv1beta1txts,
		"tx.amino": bankv1beta1txaminots,
		"tx.registry": bankv1beta1txregistryts,
		"tx.rpc.msg": bankv1beta1txrpcmsgts
	}
}
export const base = {
	abci: {
		v1beta1: {
			abci: baseabciv1beta1abcits
		}
	},
	node: {
		v1beta1: {
			query: basenodev1beta1queryts,
			"query.lcd": basenodev1beta1querylcdts,
			"query.rpc.Service": basenodev1beta1queryrpcServicets
		}
	},
	query: {
		v1beta1: {
			pagination: basequeryv1beta1paginationts
		}
	},
	v1beta1: {
		coin: basev1beta1coints
	}
}
export const consensus = {
	v1: {
		query: consensusv1queryts,
		"query.lcd": consensusv1querylcdts,
		"query.rpc.Query": consensusv1queryrpcQueryts,
		tx: consensusv1txts,
		"tx.amino": consensusv1txaminots,
		"tx.registry": consensusv1txregistryts,
		"tx.rpc.msg": consensusv1txrpcmsgts
	}
}
export const crypto = {
	ed25519: {
		keys: cryptoed25519keysts
	},
	hd: {
		v1: {
			hd: cryptohdv1hdts
		}
	},
	keyring: {
		v1: {
			record: cryptokeyringv1recordts
		}
	},
	multisig: {
		keys: cryptomultisigkeysts,
		v1beta1: {
			multisig: cryptomultisigv1beta1multisigts
		}
	},
	secp256k1: {
		keys: cryptosecp256k1keysts
	},
	secp256r1: {
		keys: cryptosecp256r1keysts
	}
}
export const distribution = {
	v1beta1: {
		distribution: distributionv1beta1distributionts,
		genesis: distributionv1beta1genesists,
		query: distributionv1beta1queryts,
		"query.lcd": distributionv1beta1querylcdts,
		"query.rpc.Query": distributionv1beta1queryrpcQueryts,
		tx: distributionv1beta1txts,
		"tx.amino": distributionv1beta1txaminots,
		"tx.registry": distributionv1beta1txregistryts,
		"tx.rpc.msg": distributionv1beta1txrpcmsgts
	}
}
export const gov = {
	v1: {
		genesis: govv1genesists,
		gov: govv1govts,
		query: govv1queryts,
		"query.lcd": govv1querylcdts,
		"query.rpc.Query": govv1queryrpcQueryts,
		tx: govv1txts,
		"tx.amino": govv1txaminots,
		"tx.registry": govv1txregistryts,
		"tx.rpc.msg": govv1txrpcmsgts
	},
	v1beta1: {
		genesis: govv1beta1genesists,
		gov: govv1beta1govts,
		query: govv1beta1queryts,
		"query.lcd": govv1beta1querylcdts,
		"query.rpc.Query": govv1beta1queryrpcQueryts,
		tx: govv1beta1txts,
		"tx.amino": govv1beta1txaminots,
		"tx.registry": govv1beta1txregistryts,
		"tx.rpc.msg": govv1beta1txrpcmsgts
	}
}
export const ics23 = {
	v1: {
		proofs: ics23v1proofsts
	}
}
export const nft = {
	v1beta1: {
		event: nftv1beta1eventts,
		genesis: nftv1beta1genesists,
		nft: nftv1beta1nftts,
		query: nftv1beta1queryts,
		"query.lcd": nftv1beta1querylcdts,
		"query.rpc.Query": nftv1beta1queryrpcQueryts,
		tx: nftv1beta1txts,
		"tx.amino": nftv1beta1txaminots,
		"tx.registry": nftv1beta1txregistryts,
		"tx.rpc.msg": nftv1beta1txrpcmsgts
	}
}
export const staking = {
	v1beta1: {
		authz: stakingv1beta1authzts,
		genesis: stakingv1beta1genesists,
		query: stakingv1beta1queryts,
		"query.lcd": stakingv1beta1querylcdts,
		"query.rpc.Query": stakingv1beta1queryrpcQueryts,
		staking: stakingv1beta1stakingts,
		tx: stakingv1beta1txts,
		"tx.amino": stakingv1beta1txaminots,
		"tx.registry": stakingv1beta1txregistryts,
		"tx.rpc.msg": stakingv1beta1txrpcmsgts
	}
}
export const tx = {
	signing: {
		v1beta1: {
			signing: txsigningv1beta1signingts
		}
	},
	v1beta1: {
		service: txv1beta1servicets,
		"service.lcd": txv1beta1servicelcdts,
		"service.rpc.Service": txv1beta1servicerpcServicets,
		tx: txv1beta1txts
	}
}
export const upgrade = {
	v1beta1: {
		query: upgradev1beta1queryts,
		"query.lcd": upgradev1beta1querylcdts,
		"query.rpc.Query": upgradev1beta1queryrpcQueryts,
		tx: upgradev1beta1txts,
		"tx.amino": upgradev1beta1txaminots,
		"tx.registry": upgradev1beta1txregistryts,
		"tx.rpc.msg": upgradev1beta1txrpcmsgts,
		upgrade: upgradev1beta1upgradets
	}
}
