/**
 * @file Automatically generated by barrelsby.
 */

import * as globalfeev1beta1genesists from "./globalfee/v1beta1/genesis"
import * as globalfeev1beta1queryts from "./globalfee/v1beta1/query"
import * as globalfeev1beta1querylcdts from "./globalfee/v1beta1/query.lcd"
import * as globalfeev1beta1queryrpcQueryts from "./globalfee/v1beta1/query.rpc.Query"
import * as globalfeev1beta1txts from "./globalfee/v1beta1/tx"
import * as globalfeev1beta1txaminots from "./globalfee/v1beta1/tx.amino"
import * as globalfeev1beta1txregistryts from "./globalfee/v1beta1/tx.registry"
import * as globalfeev1beta1txrpcmsgts from "./globalfee/v1beta1/tx.rpc.msg"
export const globalfee = {
	v1beta1: {
		genesis: globalfeev1beta1genesists,
		query: globalfeev1beta1queryts,
		"query.lcd": globalfeev1beta1querylcdts,
		"query.rpc.Query": globalfeev1beta1queryrpcQueryts,
		tx: globalfeev1beta1txts,
		"tx.amino": globalfeev1beta1txaminots,
		"tx.registry": globalfeev1beta1txregistryts,
		"tx.rpc.msg": globalfeev1beta1txrpcmsgts
	}
}
