/**
 * @file Automatically generated by barrelsby.
 */

import * as applicationsfeev1ackts from "./applications/fee/v1/ack"
import * as applicationsfeev1feets from "./applications/fee/v1/fee"
import * as applicationsfeev1genesists from "./applications/fee/v1/genesis"
import * as applicationsfeev1metadatats from "./applications/fee/v1/metadata"
import * as applicationsfeev1queryts from "./applications/fee/v1/query"
import * as applicationsfeev1querylcdts from "./applications/fee/v1/query.lcd"
import * as applicationsfeev1queryrpcQueryts from "./applications/fee/v1/query.rpc.Query"
import * as applicationsfeev1txts from "./applications/fee/v1/tx"
import * as applicationsfeev1txaminots from "./applications/fee/v1/tx.amino"
import * as applicationsfeev1txregistryts from "./applications/fee/v1/tx.registry"
import * as applicationsfeev1txrpcmsgts from "./applications/fee/v1/tx.rpc.msg"
import * as applicationsinterchain_accountscontrollerv1controllerts from "./applications/interchain_accounts/controller/v1/controller"
import * as applicationsinterchain_accountscontrollerv1queryts from "./applications/interchain_accounts/controller/v1/query"
import * as applicationsinterchain_accountscontrollerv1querylcdts from "./applications/interchain_accounts/controller/v1/query.lcd"
import * as applicationsinterchain_accountscontrollerv1queryrpcQueryts from "./applications/interchain_accounts/controller/v1/query.rpc.Query"
import * as applicationsinterchain_accountscontrollerv1txts from "./applications/interchain_accounts/controller/v1/tx"
import * as applicationsinterchain_accountscontrollerv1txaminots from "./applications/interchain_accounts/controller/v1/tx.amino"
import * as applicationsinterchain_accountscontrollerv1txregistryts from "./applications/interchain_accounts/controller/v1/tx.registry"
import * as applicationsinterchain_accountscontrollerv1txrpcmsgts from "./applications/interchain_accounts/controller/v1/tx.rpc.msg"
import * as applicationsinterchain_accountsgenesisv1genesists from "./applications/interchain_accounts/genesis/v1/genesis"
import * as applicationsinterchain_accountshostv1hostts from "./applications/interchain_accounts/host/v1/host"
import * as applicationsinterchain_accountshostv1queryts from "./applications/interchain_accounts/host/v1/query"
import * as applicationsinterchain_accountshostv1querylcdts from "./applications/interchain_accounts/host/v1/query.lcd"
import * as applicationsinterchain_accountshostv1queryrpcQueryts from "./applications/interchain_accounts/host/v1/query.rpc.Query"
import * as applicationsinterchain_accountshostv1txts from "./applications/interchain_accounts/host/v1/tx"
import * as applicationsinterchain_accountshostv1txaminots from "./applications/interchain_accounts/host/v1/tx.amino"
import * as applicationsinterchain_accountshostv1txregistryts from "./applications/interchain_accounts/host/v1/tx.registry"
import * as applicationsinterchain_accountshostv1txrpcmsgts from "./applications/interchain_accounts/host/v1/tx.rpc.msg"
import * as applicationsinterchain_accountsv1accountts from "./applications/interchain_accounts/v1/account"
import * as applicationsinterchain_accountsv1metadatats from "./applications/interchain_accounts/v1/metadata"
import * as applicationsinterchain_accountsv1packetts from "./applications/interchain_accounts/v1/packet"
import * as applicationstransferv1authzts from "./applications/transfer/v1/authz"
import * as applicationstransferv1genesists from "./applications/transfer/v1/genesis"
import * as applicationstransferv1queryts from "./applications/transfer/v1/query"
import * as applicationstransferv1querylcdts from "./applications/transfer/v1/query.lcd"
import * as applicationstransferv1queryrpcQueryts from "./applications/transfer/v1/query.rpc.Query"
import * as applicationstransferv1transferts from "./applications/transfer/v1/transfer"
import * as applicationstransferv1txts from "./applications/transfer/v1/tx"
import * as applicationstransferv1txaminots from "./applications/transfer/v1/tx.amino"
import * as applicationstransferv1txregistryts from "./applications/transfer/v1/tx.registry"
import * as applicationstransferv1txrpcmsgts from "./applications/transfer/v1/tx.rpc.msg"
import * as applicationstransferv2packetts from "./applications/transfer/v2/packet"
import * as corechannelv1channelts from "./core/channel/v1/channel"
import * as corechannelv1genesists from "./core/channel/v1/genesis"
import * as corechannelv1queryts from "./core/channel/v1/query"
import * as corechannelv1querylcdts from "./core/channel/v1/query.lcd"
import * as corechannelv1queryrpcQueryts from "./core/channel/v1/query.rpc.Query"
import * as corechannelv1txts from "./core/channel/v1/tx"
import * as corechannelv1txaminots from "./core/channel/v1/tx.amino"
import * as corechannelv1txregistryts from "./core/channel/v1/tx.registry"
import * as corechannelv1txrpcmsgts from "./core/channel/v1/tx.rpc.msg"
import * as corechannelv1upgradets from "./core/channel/v1/upgrade"
import * as coreclientv1clientts from "./core/client/v1/client"
import * as coreclientv1genesists from "./core/client/v1/genesis"
import * as coreclientv1queryts from "./core/client/v1/query"
import * as coreclientv1querylcdts from "./core/client/v1/query.lcd"
import * as coreclientv1queryrpcQueryts from "./core/client/v1/query.rpc.Query"
import * as coreclientv1txts from "./core/client/v1/tx"
import * as coreclientv1txaminots from "./core/client/v1/tx.amino"
import * as coreclientv1txregistryts from "./core/client/v1/tx.registry"
import * as coreclientv1txrpcmsgts from "./core/client/v1/tx.rpc.msg"
import * as corecommitmentv1commitmentts from "./core/commitment/v1/commitment"
import * as coreconnectionv1connectionts from "./core/connection/v1/connection"
import * as coreconnectionv1genesists from "./core/connection/v1/genesis"
import * as coreconnectionv1queryts from "./core/connection/v1/query"
import * as coreconnectionv1querylcdts from "./core/connection/v1/query.lcd"
import * as coreconnectionv1queryrpcQueryts from "./core/connection/v1/query.rpc.Query"
import * as coreconnectionv1txts from "./core/connection/v1/tx"
import * as coreconnectionv1txaminots from "./core/connection/v1/tx.amino"
import * as coreconnectionv1txregistryts from "./core/connection/v1/tx.registry"
import * as coreconnectionv1txrpcmsgts from "./core/connection/v1/tx.rpc.msg"
import * as lightclientstendermintv1tendermintts from "./lightclients/tendermint/v1/tendermint"
export const applications = {
	fee: {
		v1: {
			ack: applicationsfeev1ackts,
			fee: applicationsfeev1feets,
			genesis: applicationsfeev1genesists,
			metadata: applicationsfeev1metadatats,
			query: applicationsfeev1queryts,
			"query.lcd": applicationsfeev1querylcdts,
			"query.rpc.Query": applicationsfeev1queryrpcQueryts,
			tx: applicationsfeev1txts,
			"tx.amino": applicationsfeev1txaminots,
			"tx.registry": applicationsfeev1txregistryts,
			"tx.rpc.msg": applicationsfeev1txrpcmsgts
		}
	},
	interchain_accounts: {
		controller: {
			v1: {
				controller: applicationsinterchain_accountscontrollerv1controllerts,
				query: applicationsinterchain_accountscontrollerv1queryts,
				"query.lcd": applicationsinterchain_accountscontrollerv1querylcdts,
				"query.rpc.Query": applicationsinterchain_accountscontrollerv1queryrpcQueryts,
				tx: applicationsinterchain_accountscontrollerv1txts,
				"tx.amino": applicationsinterchain_accountscontrollerv1txaminots,
				"tx.registry": applicationsinterchain_accountscontrollerv1txregistryts,
				"tx.rpc.msg": applicationsinterchain_accountscontrollerv1txrpcmsgts
			}
		},
		genesis: {
			v1: {
				genesis: applicationsinterchain_accountsgenesisv1genesists
			}
		},
		host: {
			v1: {
				host: applicationsinterchain_accountshostv1hostts,
				query: applicationsinterchain_accountshostv1queryts,
				"query.lcd": applicationsinterchain_accountshostv1querylcdts,
				"query.rpc.Query": applicationsinterchain_accountshostv1queryrpcQueryts,
				tx: applicationsinterchain_accountshostv1txts,
				"tx.amino": applicationsinterchain_accountshostv1txaminots,
				"tx.registry": applicationsinterchain_accountshostv1txregistryts,
				"tx.rpc.msg": applicationsinterchain_accountshostv1txrpcmsgts
			}
		},
		v1: {
			account: applicationsinterchain_accountsv1accountts,
			metadata: applicationsinterchain_accountsv1metadatats,
			packet: applicationsinterchain_accountsv1packetts
		}
	},
	transfer: {
		v1: {
			authz: applicationstransferv1authzts,
			genesis: applicationstransferv1genesists,
			query: applicationstransferv1queryts,
			"query.lcd": applicationstransferv1querylcdts,
			"query.rpc.Query": applicationstransferv1queryrpcQueryts,
			transfer: applicationstransferv1transferts,
			tx: applicationstransferv1txts,
			"tx.amino": applicationstransferv1txaminots,
			"tx.registry": applicationstransferv1txregistryts,
			"tx.rpc.msg": applicationstransferv1txrpcmsgts
		},
		v2: {
			packet: applicationstransferv2packetts
		}
	}
}
export const core = {
	channel: {
		v1: {
			channel: corechannelv1channelts,
			genesis: corechannelv1genesists,
			query: corechannelv1queryts,
			"query.lcd": corechannelv1querylcdts,
			"query.rpc.Query": corechannelv1queryrpcQueryts,
			tx: corechannelv1txts,
			"tx.amino": corechannelv1txaminots,
			"tx.registry": corechannelv1txregistryts,
			"tx.rpc.msg": corechannelv1txrpcmsgts,
			upgrade: corechannelv1upgradets
		}
	},
	client: {
		v1: {
			client: coreclientv1clientts,
			genesis: coreclientv1genesists,
			query: coreclientv1queryts,
			"query.lcd": coreclientv1querylcdts,
			"query.rpc.Query": coreclientv1queryrpcQueryts,
			tx: coreclientv1txts,
			"tx.amino": coreclientv1txaminots,
			"tx.registry": coreclientv1txregistryts,
			"tx.rpc.msg": coreclientv1txrpcmsgts
		}
	},
	commitment: {
		v1: {
			commitment: corecommitmentv1commitmentts
		}
	},
	connection: {
		v1: {
			connection: coreconnectionv1connectionts,
			genesis: coreconnectionv1genesists,
			query: coreconnectionv1queryts,
			"query.lcd": coreconnectionv1querylcdts,
			"query.rpc.Query": coreconnectionv1queryrpcQueryts,
			tx: coreconnectionv1txts,
			"tx.amino": coreconnectionv1txaminots,
			"tx.registry": coreconnectionv1txregistryts,
			"tx.rpc.msg": coreconnectionv1txrpcmsgts
		}
	}
}
export const lightclients = {
	tendermint: {
		v1: {
			tendermint: lightclientstendermintv1tendermintts
		}
	}
}
