/**
 * @file Automatically generated by barrelsby.
 */

import * as tokenfactoryv1beta1authority_metadatats from "./tokenfactory/v1beta1/authority_metadata"
import * as tokenfactoryv1beta1genesists from "./tokenfactory/v1beta1/genesis"
import * as tokenfactoryv1beta1paramsts from "./tokenfactory/v1beta1/params"
import * as tokenfactoryv1beta1queryts from "./tokenfactory/v1beta1/query"
import * as tokenfactoryv1beta1querylcdts from "./tokenfactory/v1beta1/query.lcd"
import * as tokenfactoryv1beta1queryrpcQueryts from "./tokenfactory/v1beta1/query.rpc.Query"
import * as tokenfactoryv1beta1txts from "./tokenfactory/v1beta1/tx"
import * as tokenfactoryv1beta1txaminots from "./tokenfactory/v1beta1/tx.amino"
import * as tokenfactoryv1beta1txregistryts from "./tokenfactory/v1beta1/tx.registry"
import * as tokenfactoryv1beta1txrpcmsgts from "./tokenfactory/v1beta1/tx.rpc.msg"
export const tokenfactory = {
	v1beta1: {
		authority_metadata: tokenfactoryv1beta1authority_metadatats,
		genesis: tokenfactoryv1beta1genesists,
		params: tokenfactoryv1beta1paramsts,
		query: tokenfactoryv1beta1queryts,
		"query.lcd": tokenfactoryv1beta1querylcdts,
		"query.rpc.Query": tokenfactoryv1beta1queryrpcQueryts,
		tx: tokenfactoryv1beta1txts,
		"tx.amino": tokenfactoryv1beta1txaminots,
		"tx.registry": tokenfactoryv1beta1txregistryts,
		"tx.rpc.msg": tokenfactoryv1beta1txrpcmsgts
	}
}
