/**
 * @file Automatically generated by barrelsby.
 */

import * as clockv1clockts from "./clock/v1/clock"
import * as clockv1genesists from "./clock/v1/genesis"
import * as clockv1queryts from "./clock/v1/query"
import * as clockv1querylcdts from "./clock/v1/query.lcd"
import * as clockv1queryrpcQueryts from "./clock/v1/query.rpc.Query"
import * as clockv1txts from "./clock/v1/tx"
import * as clockv1txaminots from "./clock/v1/tx.amino"
import * as clockv1txregistryts from "./clock/v1/tx.registry"
import * as clockv1txrpcmsgts from "./clock/v1/tx.rpc.msg"
import * as cwhooksv1genesists from "./cwhooks/v1/genesis"
import * as cwhooksv1queryts from "./cwhooks/v1/query"
import * as cwhooksv1querylcdts from "./cwhooks/v1/query.lcd"
import * as cwhooksv1queryrpcQueryts from "./cwhooks/v1/query.rpc.Query"
import * as cwhooksv1txts from "./cwhooks/v1/tx"
import * as cwhooksv1txaminots from "./cwhooks/v1/tx.amino"
import * as cwhooksv1txregistryts from "./cwhooks/v1/tx.registry"
import * as cwhooksv1txrpcmsgts from "./cwhooks/v1/tx.rpc.msg"
import * as dripv1genesists from "./drip/v1/genesis"
import * as dripv1queryts from "./drip/v1/query"
import * as dripv1querylcdts from "./drip/v1/query.lcd"
import * as dripv1queryrpcQueryts from "./drip/v1/query.rpc.Query"
import * as dripv1txts from "./drip/v1/tx"
import * as dripv1txaminots from "./drip/v1/tx.amino"
import * as dripv1txregistryts from "./drip/v1/tx.registry"
import * as dripv1txrpcmsgts from "./drip/v1/tx.rpc.msg"
import * as feepayv1feepayts from "./feepay/v1/feepay"
import * as feepayv1genesists from "./feepay/v1/genesis"
import * as feepayv1queryts from "./feepay/v1/query"
import * as feepayv1querylcdts from "./feepay/v1/query.lcd"
import * as feepayv1queryrpcQueryts from "./feepay/v1/query.rpc.Query"
import * as feepayv1txts from "./feepay/v1/tx"
import * as feepayv1txaminots from "./feepay/v1/tx.amino"
import * as feepayv1txregistryts from "./feepay/v1/tx.registry"
import * as feepayv1txrpcmsgts from "./feepay/v1/tx.rpc.msg"
import * as feesharev1feesharets from "./feeshare/v1/feeshare"
import * as feesharev1genesists from "./feeshare/v1/genesis"
import * as feesharev1queryts from "./feeshare/v1/query"
import * as feesharev1querylcdts from "./feeshare/v1/query.lcd"
import * as feesharev1queryrpcQueryts from "./feeshare/v1/query.rpc.Query"
import * as feesharev1txts from "./feeshare/v1/tx"
import * as feesharev1txaminots from "./feeshare/v1/tx.amino"
import * as feesharev1txregistryts from "./feeshare/v1/tx.registry"
import * as feesharev1txrpcmsgts from "./feeshare/v1/tx.rpc.msg"
import * as mintv1genesists from "./mint/v1/genesis"
import * as mintv1mintts from "./mint/v1/mint"
import * as mintv1queryts from "./mint/v1/query"
import * as mintv1querylcdts from "./mint/v1/query.lcd"
import * as mintv1queryrpcQueryts from "./mint/v1/query.rpc.Query"
import * as mintv1txts from "./mint/v1/tx"
import * as mintv1txaminots from "./mint/v1/tx.amino"
import * as mintv1txregistryts from "./mint/v1/tx.registry"
import * as mintv1txrpcmsgts from "./mint/v1/tx.rpc.msg"
export const clock = {
	v1: {
		clock: clockv1clockts,
		genesis: clockv1genesists,
		query: clockv1queryts,
		"query.lcd": clockv1querylcdts,
		"query.rpc.Query": clockv1queryrpcQueryts,
		tx: clockv1txts,
		"tx.amino": clockv1txaminots,
		"tx.registry": clockv1txregistryts,
		"tx.rpc.msg": clockv1txrpcmsgts
	}
}
export const cwhooks = {
	v1: {
		genesis: cwhooksv1genesists,
		query: cwhooksv1queryts,
		"query.lcd": cwhooksv1querylcdts,
		"query.rpc.Query": cwhooksv1queryrpcQueryts,
		tx: cwhooksv1txts,
		"tx.amino": cwhooksv1txaminots,
		"tx.registry": cwhooksv1txregistryts,
		"tx.rpc.msg": cwhooksv1txrpcmsgts
	}
}
export const drip = {
	v1: {
		genesis: dripv1genesists,
		query: dripv1queryts,
		"query.lcd": dripv1querylcdts,
		"query.rpc.Query": dripv1queryrpcQueryts,
		tx: dripv1txts,
		"tx.amino": dripv1txaminots,
		"tx.registry": dripv1txregistryts,
		"tx.rpc.msg": dripv1txrpcmsgts
	}
}
export const feepay = {
	v1: {
		feepay: feepayv1feepayts,
		genesis: feepayv1genesists,
		query: feepayv1queryts,
		"query.lcd": feepayv1querylcdts,
		"query.rpc.Query": feepayv1queryrpcQueryts,
		tx: feepayv1txts,
		"tx.amino": feepayv1txaminots,
		"tx.registry": feepayv1txregistryts,
		"tx.rpc.msg": feepayv1txrpcmsgts
	}
}
export const feeshare = {
	v1: {
		feeshare: feesharev1feesharets,
		genesis: feesharev1genesists,
		query: feesharev1queryts,
		"query.lcd": feesharev1querylcdts,
		"query.rpc.Query": feesharev1queryrpcQueryts,
		tx: feesharev1txts,
		"tx.amino": feesharev1txaminots,
		"tx.registry": feesharev1txregistryts,
		"tx.rpc.msg": feesharev1txrpcmsgts
	}
}
export const mint = {
	v1: {
		genesis: mintv1genesists,
		mint: mintv1mintts,
		query: mintv1queryts,
		"query.lcd": mintv1querylcdts,
		"query.rpc.Query": mintv1queryrpcQueryts,
		tx: mintv1txts,
		"tx.amino": mintv1txaminots,
		"tx.registry": mintv1txregistryts,
		"tx.rpc.msg": mintv1txrpcmsgts
	}
}
