/**
 * @file Automatically generated by barrelsby.
 */

import * as wasmv1authzts from "./wasm/v1/authz"
import * as wasmv1genesists from "./wasm/v1/genesis"
import * as wasmv1ibcts from "./wasm/v1/ibc"
import * as wasmv1proposal_legacyts from "./wasm/v1/proposal_legacy"
import * as wasmv1queryts from "./wasm/v1/query"
import * as wasmv1querylcdts from "./wasm/v1/query.lcd"
import * as wasmv1queryrpcQueryts from "./wasm/v1/query.rpc.Query"
import * as wasmv1txts from "./wasm/v1/tx"
import * as wasmv1txaminots from "./wasm/v1/tx.amino"
import * as wasmv1txregistryts from "./wasm/v1/tx.registry"
import * as wasmv1txrpcmsgts from "./wasm/v1/tx.rpc.msg"
import * as wasmv1typests from "./wasm/v1/types"
export const wasm = {
	v1: {
		authz: wasmv1authzts,
		genesis: wasmv1genesists,
		ibc: wasmv1ibcts,
		proposal_legacy: wasmv1proposal_legacyts,
		query: wasmv1queryts,
		"query.lcd": wasmv1querylcdts,
		"query.rpc.Query": wasmv1queryrpcQueryts,
		tx: wasmv1txts,
		"tx.amino": wasmv1txaminots,
		"tx.registry": wasmv1txregistryts,
		"tx.rpc.msg": wasmv1txrpcmsgts,
		types: wasmv1typests
	}
}
